"""add execution trace fields to queries

Revision ID: 3412d6ca3ee1
Revises: 93227407ec1b
Create Date: 2026-09-17 01:05:49.596040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3412d6ca3ee1'
down_revision: Union[str, Sequence[str], None] = '93227407ec1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('trace_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('queries', sa.Column('compatibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('queries', sa.Column('confidence_source', sa.String(length=50), nullable=True))
    op.add_column('queries', sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('queries', sa.Column('used_fallback', sa.Boolean(), nullable=True))
    op.add_column('queries', sa.Column('specialist_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'specialist_id')
    op.drop_column('queries', 'used_fallback')
    op.drop_column('queries', 'warnings')
    op.drop_column('queries', 'confidence_source')
    op.drop_column('queries', 'compatibility')
    op.drop_column('queries', 'trace_events')
    # ### end Alembic commands ###
