"""add raster metadata fields to images

Revision ID: 93227407ec1b
Revises: c11e454b7c43
Create Date: 2026-09-16 22:52:16.116031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93227407ec1b'
down_revision: Union[str, Sequence[str], None] = 'c11e454b7c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('band_count', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('dtype', sa.String(length=20), nullable=True))
    op.add_column('images', sa.Column('bounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('images', sa.Column('bounds_wgs84', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('images', sa.Column('transform', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('images', sa.Column('nodata', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('file_format', sa.String(length=20), nullable=True))
    op.add_column('images', sa.Column('is_georeferenced', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('acquisition_date_source', sa.String(length=20), nullable=True))
    op.add_column('images', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('metadata_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('images', 'crs',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'crs',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('images', 'metadata_warnings')
    op.drop_column('images', 'file_size_bytes')
    op.drop_column('images', 'acquisition_date_source')
    op.drop_column('images', 'is_georeferenced')
    op.drop_column('images', 'file_format')
    op.drop_column('images', 'nodata')
    op.drop_column('images', 'transform')
    op.drop_column('images', 'bounds_wgs84')
    op.drop_column('images', 'bounds')
    op.drop_column('images', 'dtype')
    op.drop_column('images', 'band_count')
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    # ### end Alembic commands ###
