"""create initial tables

Revision ID: c11e454b7c43
Revises: 
Create Date: 2026-09-10 15:25:35.022332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c11e454b7c43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('crs', sa.String(length=50), nullable=True),
    sa.Column('bbox_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('image_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('task_classified', sa.String(length=50), nullable=True),
    sa.Column('selected_tool', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('bounding_boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_mask_path', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_results')
    op.drop_table('queries')
    op.drop_table('images')
    # ### end Alembic commands ###
